/// Physician specialties offered by the registration autocomplete.
///
/// Order is the clinical grouping the list was supplied in (internal medicine
/// and its subspecialties, then family, pediatrics, and so on) rather than
/// alphabetical, so browsing without typing still reads sensibly. Duplicates
/// in the source list were dropped — a picker must never show the same entry
/// twice.
class Specialties {
  Specialties._();

  /// Escape hatch, always offered last. Choosing it clears the field so the
  /// physician can type something the list does not cover.
  static const String other = 'Other';

  static const List<String> all = [
    'Internal Medicine',
    'Cardiology',
    'Interventional Cardiology',
    'Electrophysiology',
    'Endocrinology, Diabetes & Metabolism',
    'Gastroenterology',
    'Hepatology',
    'Hematology',
    'Medical Oncology',
    'Hematology-Oncology',
    'Infectious Disease',
    'Nephrology',
    'Pulmonary Disease',
    'Critical Care Medicine',
    'Pulmonary & Critical Care Medicine',
    'Rheumatology',
    'Allergy & Immunology',
    'Geriatric Medicine',
    'Hospital Medicine',
    'Sleep Medicine',
    'Clinical Pharmacology',
    'Family Medicine',
    'Sports Medicine',
    'Hospice & Palliative Medicine',
    'Adolescent Medicine',
    'Pediatrics',
    'Neonatal-Perinatal Medicine',
    'Pediatric Cardiology',
    'Pediatric Endocrinology',
    'Pediatric Gastroenterology',
    'Pediatric Hematology-Oncology',
    'Pediatric Infectious Disease',
    'Pediatric Nephrology',
    'Pediatric Pulmonology',
    'Pediatric Rheumatology',
    'Pediatric Critical Care',
    'Developmental-Behavioral Pediatrics',
    'Pediatric Emergency Medicine',
    'Emergency Medicine',
    'Emergency Medical Services',
    'Medical Toxicology',
    'Neurology',
    'Vascular Neurology / Stroke Medicine',
    'Epilepsy',
    'Neuromuscular Medicine',
    'Movement Disorders',
    'Headache Medicine',
    'Neurocritical Care',
    'Behavioral Neurology',
    'Clinical Neurophysiology',
    'Psychiatry',
    'Child & Adolescent Psychiatry',
    'Addiction Psychiatry',
    'Geriatric Psychiatry',
    'Forensic Psychiatry',
    'Consultation-Liaison Psychiatry',
    'Dermatology',
    'Dermatopathology',
    'Pediatric Dermatology',
    'Procedural Dermatology / Mohs Surgery',
    'Physical Medicine & Rehabilitation',
    'Pain Medicine',
    'Spinal Cord Injury Medicine',
    'Brain Injury Medicine',
    'Neuromuscular Rehabilitation',
    'Preventive Medicine',
    'Public Health & General Preventive Medicine',
    'Occupational Medicine',
    'Aerospace Medicine',
    'Addiction Medicine',
    'Medical Genetics & Genomics',
    'Clinical Genetics',
    'Clinical Biochemical Genetics',
    'Molecular Genetic Pathology',
    'Obstetrics & Gynecology',
    'Maternal-Fetal Medicine',
    'Gynecologic Oncology',
    'Reproductive Endocrinology & Infertility',
    'Female Pelvic Medicine & Reconstructive Surgery',
    'General Surgery',
    'Vascular Surgery',
    'Surgical Oncology',
    'Trauma Surgery',
    'Critical Care Surgery',
    'Colorectal Surgery',
    'Transplant Surgery',
    'Pediatric Surgery',
    'Bariatric / Metabolic Surgery',
    'Orthopedic Surgery',
    'Hand Surgery',
    'Spine Surgery',
    'Joint Replacement',
    'Orthopedic Trauma',
    'Pediatric Orthopedics',
    'Foot & Ankle Surgery',
    'Neurosurgery',
    'Cardiothoracic Surgery',
    'Cardiac Surgery',
    'Thoracic Surgery',
    'Congenital Cardiac Surgery',
    'Plastic Surgery',
    'Reconstructive Surgery',
    'Cosmetic Surgery',
    'Craniofacial Surgery',
    'Otolaryngology / ENT',
    'Head & Neck Surgery',
    'Otology / Neurotology',
    'Rhinology',
    'Laryngology',
    'Pediatric ENT',
    'Facial Plastic Surgery',
    'Ophthalmology',
    'Retina',
    'Cornea',
    'Glaucoma',
    'Neuro-Ophthalmology',
    'Pediatric Ophthalmology',
    'Oculoplastic Surgery',
    'Urology',
    'Urologic Oncology',
    'Pediatric Urology',
    'Female Pelvic Medicine',
    'Male Infertility / Andrology',
    'Endourology',
    'Anesthesiology',
    'Cardiothoracic Anesthesiology',
    'Pediatric Anesthesiology',
    'Obstetric Anesthesiology',
    'Radiology',
    'Diagnostic Radiology',
    'Interventional Radiology',
    'Neuroradiology',
    'Nuclear Radiology',
    'Pediatric Radiology',
    'Breast Imaging',
    'Musculoskeletal Radiology',
    'Pathology',
    'Anatomic Pathology',
    'Clinical Pathology',
    'Hematopathology',
    'Cytopathology',
    'Neuropathology',
    'Forensic Pathology',
    'Radiation Oncology',
    'Nuclear Medicine',
  ];

  /// Case-insensitive substring match, plus [other] pinned to the end.
  /// An empty query lists everything, so tapping the field browses the lot.
  static List<String> matching(String query) {
    final q = query.trim().toLowerCase();
    final hits = q.isEmpty
        ? all
        : all.where((s) => s.toLowerCase().contains(q)).toList();
    return [...hits, other];
  }
}
