"""API models module."""

from api.models.profile import (
    ProfileModel,
    ProfileCreate,
    ProfileUpdate,
    AddressModel,
)
from api.models.messaging import (
    ConversationModel,
    ConversationSettings,
    ConversationCreate,
    MessageModel,
    MessageCreate,
    MessageStatus,
    MessageType,
    FileInfo,
    AudioInfo,
    LastMessage,
    MessagingPreferencesModel,
    MessagingPreferencesUpdate,
    WhoCanMessage,
)
from api.models.connection import (
    ConnectionModel,
    ConnectionStatus,
    ConnectionCreate,
    NetworkContactModel,
    PendingRequestModel,
    SuggestedContactModel,
    BlockedUserModel,
    UserReportModel,
    UserReportCreate,
)
from api.models.organization import (
    OrganizationModel,
    OrganizationCreate,
    OrganizationType,
    MemberRole,
    MemberStatus,
    OrganizationMembershipModel,
    MyOrganizationModel,
    DepartmentModel,
    DepartmentCreate,
    ColleagueModel,
    OrganizationInviteModel,
    OrganizationInviteCreate,
)

__all__ = [
    # Profile
    "ProfileModel",
    "ProfileCreate",
    "ProfileUpdate",
    "AddressModel",
    # Messaging
    "ConversationModel",
    "ConversationSettings",
    "ConversationCreate",
    "MessageModel",
    "MessageCreate",
    "MessageStatus",
    "MessageType",
    "FileInfo",
    "AudioInfo",
    "LastMessage",
    "MessagingPreferencesModel",
    "MessagingPreferencesUpdate",
    "WhoCanMessage",
    # Connection
    "ConnectionModel",
    "ConnectionStatus",
    "ConnectionCreate",
    "NetworkContactModel",
    "PendingRequestModel",
    "SuggestedContactModel",
    "BlockedUserModel",
    "UserReportModel",
    "UserReportCreate",
    # Organization
    "OrganizationModel",
    "OrganizationCreate",
    "OrganizationType",
    "MemberRole",
    "MemberStatus",
    "OrganizationMembershipModel",
    "MyOrganizationModel",
    "DepartmentModel",
    "DepartmentCreate",
    "ColleagueModel",
    "OrganizationInviteModel",
    "OrganizationInviteCreate",
]
